### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by gygitlab** [gdraheim/docker-copyedit#10]
Alpine has recently got rid of Python2, which is needed for this (awesome) script.

While this is workaround-able for now I was wondering if there was ever any plans to support Python 3?

**Comment by gdraheim** [comment]
The python3 compatibility had been intended from the start but it was missing actual testing.

I have updated the testsuite to allow for selection of a python3 interpreter, and the few errors are fixed now.

Please give it a test if it works for you.

**Comment by gy-gl** [comment]
Thanks @gdraheim. Had a check there and it still fails on this line - https://github.com/gdraheim/docker-copyedit/blob/master/docker-copyedit.py#L539

Looks like a missed except?

**Comment by grantyoung** [comment]
Hmm after fixing that I'm seeing another issue:

```python3 ./docker-copyedit.py FROM gitlab/gitlab-ce:12.5.0-ce.0 INTO no-volumes/gitlab-ce:12.5.0-ce.0 REMOVE ALL VOLUME
ERROR:edit:can not do edit remove volume *
ERROR:edit:can not do edit remove volume *
```

Worked fine before.

**Comment by gdraheim** [comment]
It did work on my disk but I did just notice that I had merged some patches that were created before modifying the master branch to Python3. The merge algorithm did somehow manage to revert one of the "except" usages. It is fixed now, thank's for checking that.

**Comment by gdraheim** [comment]
I have converted the source code to run with Python 3 by default. That includes the testsuite and I have added type hints.
